# Generated by Django 3.2.3 on 2021-05-20 15:08
from django.contrib.auth.models import User
from django.db import migrations

def initialize_data(apps, schema_editor):
    admin = User.objects.create_user(username='admin', password='password', is_superuser=True, is_staff=True)
    admin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_data)
    ]
