# Generated by Django 3.2.3 on 2021-05-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='musicians',
            field=models.ManyToManyField(to='music.Instrument'),
        ),
        migrations.CreateModel(
            name='MusicianBandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.band')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician')),
            ],
        ),
    ]
