# Generated by Django 3.2.3 on 2021-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_instrument_creation_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='musicians',
            new_name='instruments',
        ),
    ]
