# Generated by Django 3.2.3 on 2021-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210521_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='bands',
            field=models.ManyToManyField(blank=True, null=True, to='music.Band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
