# Generated by Django 3.2.3 on 2021-05-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210521_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcontribution',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album'),
            preserve_default=False,
        ),
    ]
