# Generated by Django 3.2.3 on 2021-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='bands',
            field=models.ManyToManyField(to='music.Band'),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
