# Generated by Django 3.2.3 on 2021-05-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210522_1208'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='albumreview',
            constraint=models.UniqueConstraint(fields=('author', 'album'), name='one_review_per_user_per_album'),
        ),
    ]
