# Generated by Django 3.2.3 on 2021-05-22 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_albumreview_one_review_per_user_per_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
